import type { ApplicantProfileInput, DemoScenario } from "@/lib/types";

const baseInput: ApplicantProfileInput = {
  useCase: "tenant_screening",
  personalInformation: {
    fullName: "Jordan Rivera",
    email: "jordan@example.com",
    phone: "(555) 410-2298",
    city: "Raleigh",
    state: "NC",
    targetRent: 1850,
  },
  identityVerification: {
    identityMethod: "government_id",
    identityVerified: true,
    governmentIdFileNames: ["north-carolina-id.pdf"],
    accountOwnerMatch: true,
  },
  employmentIncome: {
    employmentStatus: "full_time",
    employerName: "Triangle Health Systems",
    monthlyIncome: 5400,
    incomeType: "salary",
    payFrequency: "biweekly",
    payStubFileNames: ["paystub-february.pdf"],
    contractDocumentFileNames: [],
  },
  housingHistory: {
    currentRent: 1680,
    monthsAtResidence: 14,
    rentPaymentStreakMonths: 11,
    utilityPaymentStreakMonths: 8,
    leaseFileNames: ["lease-renewal.pdf"],
    rentLedgerFileNames: ["rent-ledger-q1.pdf"],
    receiptsFileNames: ["rent-receipt-march.pdf"],
    landlordReferenceName: "Ms. Owens",
  },
  financialStability: {
    bankConnected: true,
    averageBalanceCushion: 2900,
    overdraftsLast90Days: 0,
    recurringBillsTracked: true,
    signalRecencyDays: 18,
    contradictionDetected: false,
  },
  supportingDocuments: {
    additionalFileNames: ["utility-bill.pdf"],
  },
  consents: {
    identity_check: true,
    bank_connection: true,
    income_docs: true,
    housing_docs: true,
    consentToSubmit: true,
    retentionAcknowledged: true,
  },
};

export const demoScenarios: DemoScenario[] = [
  {
    key: "newcomer",
    label: "Newcomer with strong rent history",
    description:
      "Good for the primary demo. Strong housing records, stable income, and connected financial signals.",
    input: baseInput,
  },
  {
    key: "gig_worker",
    label: "Gig worker with uneven income",
    description:
      "Shows that variable income does not automatically translate to high risk when payments are still consistent.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Samira Patel",
        email: "samira@example.com",
        targetRent: 1650,
      },
      employmentIncome: {
        employmentStatus: "gig_worker",
        employerName: "",
        monthlyIncome: 4700,
        incomeType: "gig",
        payFrequency: "irregular",
        payStubFileNames: [],
        contractDocumentFileNames: ["platform-payout-summary.pdf"],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1520,
        monthsAtResidence: 12,
        rentPaymentStreakMonths: 9,
        utilityPaymentStreakMonths: 6,
        rentLedgerFileNames: ["rent-receipts-q1.pdf"],
        receiptsFileNames: [],
        landlordReferenceName: "",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 1800,
        overdraftsLast90Days: 1,
      },
      supportingDocuments: {
        additionalFileNames: [],
      },
    },
  },
  {
    key: "student",
    label: "Student with thin-file profile",
    description:
      "Shows low confidence and manual review rather than treating limited data like bad behavior.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Maya Chen",
        email: "maya@example.com",
        targetRent: 1300,
      },
      employmentIncome: {
        employmentStatus: "student",
        employerName: "Campus Library",
        monthlyIncome: 2450,
        incomeType: "mixed",
        payFrequency: "monthly",
        payStubFileNames: ["campus-job-letter.pdf"],
        contractDocumentFileNames: [],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1100,
        monthsAtResidence: 5,
        rentPaymentStreakMonths: 3,
        utilityPaymentStreakMonths: 1,
        leaseFileNames: [],
        rentLedgerFileNames: ["roommate-ledger.pdf"],
        landlordReferenceName: "",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 1100,
        overdraftsLast90Days: 1,
        signalRecencyDays: 9,
      },
      supportingDocuments: {
        additionalFileNames: [],
      },
    },
  },
  {
    key: "inconsistency",
    label: "Profile with inconsistency flag",
    description:
      "Useful for demonstrating that Credora escalates conflicts to manual review rather than pretending certainty.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Luis Romero",
        email: "luis@example.com",
        targetRent: 2100,
      },
      identityVerification: {
        ...baseInput.identityVerification,
        accountOwnerMatch: false,
      },
      employmentIncome: {
        employmentStatus: "self_employed",
        employerName: "Romero Design Co.",
        monthlyIncome: 6000,
        incomeType: "contract",
        payFrequency: "irregular",
        payStubFileNames: [],
        contractDocumentFileNames: ["contract-summary.pdf", "bank-deposit-export.csv"],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1890,
        monthsAtResidence: 10,
        rentPaymentStreakMonths: 7,
        utilityPaymentStreakMonths: 4,
        rentLedgerFileNames: ["rent-receipts.pdf"],
        landlordReferenceName: "",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 2400,
        overdraftsLast90Days: 2,
        contradictionDetected: true,
      },
      supportingDocuments: {
        additionalFileNames: [],
      },
    },
  },
  {
    key: "travel_nurse",
    label: "Travel nurse with verified housing continuity",
    description:
      "Shows a strong, mobile professional profile with verified income and consistent housing records.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Avery Brooks",
        email: "avery@example.com",
        city: "Charlotte",
        targetRent: 2200,
      },
      employmentIncome: {
        employmentStatus: "full_time",
        employerName: "Blue Harbor Clinical Staffing",
        monthlyIncome: 7800,
        incomeType: "contract",
        payFrequency: "biweekly",
        payStubFileNames: ["travel-nurse-paystub.pdf"],
        contractDocumentFileNames: ["assignment-letter.pdf"],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1950,
        monthsAtResidence: 18,
        rentPaymentStreakMonths: 18,
        utilityPaymentStreakMonths: 15,
        landlordReferenceName: "Carla Jenkins",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 3600,
        signalRecencyDays: 6,
      },
    },
  },
  {
    key: "hourly_worker",
    label: "Hourly worker with steady local history",
    description:
      "Shows solid payment behavior, moderate income stability, and strong rent continuity without a premium salary profile.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Noah Carter",
        email: "noah@example.com",
        city: "Greensboro",
        targetRent: 1450,
      },
      employmentIncome: {
        employmentStatus: "part_time",
        employerName: "Piedmont Fresh Market",
        monthlyIncome: 3600,
        incomeType: "hourly",
        payFrequency: "weekly",
        payStubFileNames: ["weekly-paystubs.pdf"],
        contractDocumentFileNames: [],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1280,
        monthsAtResidence: 22,
        rentPaymentStreakMonths: 20,
        utilityPaymentStreakMonths: 18,
        landlordReferenceName: "Darius Cole",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 1500,
        overdraftsLast90Days: 0,
        signalRecencyDays: 11,
      },
    },
  },
  {
    key: "corporate_accountant",
    label: "Corporate accountant with premium documentation",
    description:
      "High-confidence profile with strong income coverage, long rent continuity, and fresh verified financial signals.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Daniel Kim",
        email: "daniel@example.com",
        city: "Atlanta",
        state: "GA",
        targetRent: 2400,
      },
      employmentIncome: {
        employmentStatus: "full_time",
        employerName: "Stonebridge Advisory",
        monthlyIncome: 9200,
        incomeType: "salary",
        payFrequency: "semi_monthly",
        payStubFileNames: ["march-paystub.pdf", "february-paystub.pdf"],
        contractDocumentFileNames: ["employment-verification-letter.pdf"],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 2100,
        monthsAtResidence: 28,
        rentPaymentStreakMonths: 24,
        utilityPaymentStreakMonths: 24,
        landlordReferenceName: "Helen Strauss",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 6200,
        signalRecencyDays: 4,
      },
    },
  },
  {
    key: "new_city_engineer",
    label: "Engineer new to the city with short but clean history",
    description:
      "Shorter residence history but strong verified income and clean bank-linked signals.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Olivia Bennett",
        email: "olivia@example.com",
        city: "Austin",
        state: "TX",
        targetRent: 2100,
      },
      employmentIncome: {
        employmentStatus: "full_time",
        employerName: "Nova Systems",
        monthlyIncome: 7800,
        incomeType: "salary",
        payFrequency: "biweekly",
        payStubFileNames: ["recent-paystub.pdf"],
        contractDocumentFileNames: [],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1920,
        monthsAtResidence: 6,
        rentPaymentStreakMonths: 6,
        utilityPaymentStreakMonths: 5,
        landlordReferenceName: "Tara Sloan",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 4100,
        signalRecencyDays: 5,
      },
    },
  },
  {
    key: "restaurant_manager",
    label: "Restaurant manager with solid but not premium profile",
    description:
      "Good continuity and verified records, but with tighter income coverage and a more moderate financial cushion.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Elena Garcia",
        email: "elena@example.com",
        city: "Tampa",
        state: "FL",
        targetRent: 1700,
      },
      employmentIncome: {
        employmentStatus: "full_time",
        employerName: "Harbor Table Group",
        monthlyIncome: 3850,
        incomeType: "salary",
        payFrequency: "biweekly",
        payStubFileNames: ["manager-paystub.pdf"],
        contractDocumentFileNames: [],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1500,
        monthsAtResidence: 16,
        rentPaymentStreakMonths: 14,
        utilityPaymentStreakMonths: 11,
        landlordReferenceName: "Marco Alvarez",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 1200,
        overdraftsLast90Days: 1,
        signalRecencyDays: 13,
      },
    },
  },
  {
    key: "rideshare_driver",
    label: "Rideshare driver with volatile cash flow",
    description:
      "Verified but noisier profile that should still read as usable rather than automatically high risk.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Marcus Lee",
        email: "marcus@example.com",
        city: "Phoenix",
        state: "AZ",
        targetRent: 1550,
      },
      employmentIncome: {
        employmentStatus: "gig_worker",
        employerName: "Metro Ride Platforms",
        monthlyIncome: 3400,
        incomeType: "gig",
        payFrequency: "irregular",
        payStubFileNames: [],
        contractDocumentFileNames: ["platform-payout-history.pdf"],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1400,
        monthsAtResidence: 8,
        rentPaymentStreakMonths: 7,
        utilityPaymentStreakMonths: 5,
        receiptsFileNames: ["rent-screenshots.pdf"],
        landlordReferenceName: "",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 900,
        overdraftsLast90Days: 2,
        signalRecencyDays: 10,
      },
    },
  },
  {
    key: "postdoc_researcher",
    label: "Postdoctoral researcher with thin but credible file",
    description:
      "Limited housing depth but steady documented stipend income and clean payment behavior.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Priya Desai",
        email: "priya@example.com",
        city: "New Haven",
        state: "CT",
        targetRent: 1600,
      },
      employmentIncome: {
        employmentStatus: "full_time",
        employerName: "Easton Biomedical Lab",
        monthlyIncome: 4100,
        incomeType: "stipend",
        payFrequency: "monthly",
        payStubFileNames: ["stipend-letter.pdf"],
        contractDocumentFileNames: [],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1450,
        monthsAtResidence: 4,
        rentPaymentStreakMonths: 4,
        utilityPaymentStreakMonths: 3,
        leaseFileNames: ["graduate-housing-lease.pdf"],
        rentLedgerFileNames: [],
        receiptsFileNames: [],
        landlordReferenceName: "",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 1700,
        signalRecencyDays: 8,
      },
    },
  },
  {
    key: "warehouse_shift_lead",
    label: "Warehouse shift lead with lower score but complete file",
    description:
      "A complete profile that still lands lower because of tighter finances and recent overdrafts, not missing data.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Ethan Walker",
        email: "ethan@example.com",
        city: "Columbus",
        state: "OH",
        targetRent: 1750,
      },
      employmentIncome: {
        employmentStatus: "full_time",
        employerName: "Summit Distribution",
        monthlyIncome: 3300,
        incomeType: "hourly",
        payFrequency: "weekly",
        payStubFileNames: ["warehouse-paystubs.pdf"],
        contractDocumentFileNames: [],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1580,
        monthsAtResidence: 11,
        rentPaymentStreakMonths: 8,
        utilityPaymentStreakMonths: 6,
        landlordReferenceName: "Pam Brooks",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 650,
        overdraftsLast90Days: 3,
        signalRecencyDays: 15,
      },
    },
  },
  {
    key: "between_roles_designer",
    label: "Designer between roles with limited current cushion",
    description:
      "Useful middle-to-lower profile showing that completed evidence can still lead to manual review when current stability is weaker.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Sofia Nguyen",
        email: "sofia@example.com",
        city: "Portland",
        state: "OR",
        targetRent: 1800,
      },
      employmentIncome: {
        employmentStatus: "between_roles",
        employerName: "Freelance / between engagements",
        monthlyIncome: 2900,
        incomeType: "mixed",
        payFrequency: "irregular",
        payStubFileNames: ["final-paystub.pdf"],
        contractDocumentFileNames: ["portfolio-contract.pdf"],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1625,
        monthsAtResidence: 9,
        rentPaymentStreakMonths: 9,
        utilityPaymentStreakMonths: 7,
        landlordReferenceName: "Naomi Price",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 700,
        overdraftsLast90Days: 2,
        signalRecencyDays: 16,
      },
    },
  },
  {
    key: "field_technician",
    label: "Field technician with strong continuity",
    description:
      "Strong but not perfect profile with steady records and slightly more modest housing and balance metrics.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Caleb Foster",
        email: "caleb@example.com",
        city: "Nashville",
        state: "TN",
        targetRent: 1700,
      },
      employmentIncome: {
        employmentStatus: "full_time",
        employerName: "Southline Utilities",
        monthlyIncome: 5200,
        incomeType: "hourly",
        payFrequency: "biweekly",
        payStubFileNames: ["tech-paystub.pdf"],
        contractDocumentFileNames: [],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1480,
        monthsAtResidence: 20,
        rentPaymentStreakMonths: 18,
        utilityPaymentStreakMonths: 15,
        landlordReferenceName: "Terrence Hall",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 2100,
        overdraftsLast90Days: 0,
        signalRecencyDays: 9,
      },
    },
  },
  {
    key: "retail_cashier",
    label: "Retail cashier with stressed short-term stability",
    description:
      "Complete file, but lower-scoring because income coverage is tight and recent cash-flow stress is visible.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Renee Wallace",
        email: "renee@example.com",
        city: "Jacksonville",
        state: "FL",
        targetRent: 1650,
      },
      identityVerification: {
        ...baseInput.identityVerification,
        identityVerified: false,
      },
      employmentIncome: {
        employmentStatus: "part_time",
        employerName: "Harbor Retail Group",
        monthlyIncome: 2600,
        incomeType: "hourly",
        payFrequency: "weekly",
        payStubFileNames: ["retail-paystub.pdf"],
        contractDocumentFileNames: [],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1490,
        monthsAtResidence: 6,
        rentPaymentStreakMonths: 5,
        utilityPaymentStreakMonths: 4,
        landlordReferenceName: "",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 420,
        overdraftsLast90Days: 4,
        signalRecencyDays: 18,
      },
    },
  },
  {
    key: "freelance_editor_conflict",
    label: "Freelance editor with conflict flag",
    description:
      "Low-confidence profile that demonstrates visible contradiction handling instead of overstating certainty.",
    input: {
      ...baseInput,
      personalInformation: {
        ...baseInput.personalInformation,
        fullName: "Omar Hassan",
        email: "omar@example.com",
        city: "Baltimore",
        state: "MD",
        targetRent: 1900,
      },
      identityVerification: {
        ...baseInput.identityVerification,
        identityVerified: false,
        accountOwnerMatch: false,
      },
      employmentIncome: {
        employmentStatus: "self_employed",
        employerName: "Independent editorial services",
        monthlyIncome: 3100,
        incomeType: "contract",
        payFrequency: "irregular",
        payStubFileNames: [],
        contractDocumentFileNames: ["client-contracts.pdf"],
      },
      housingHistory: {
        ...baseInput.housingHistory,
        currentRent: 1760,
        monthsAtResidence: 7,
        rentPaymentStreakMonths: 4,
        utilityPaymentStreakMonths: 3,
        rentLedgerFileNames: [],
        receiptsFileNames: ["rent-app-transfers.pdf"],
        landlordReferenceName: "",
      },
      financialStability: {
        ...baseInput.financialStability,
        averageBalanceCushion: 500,
        overdraftsLast90Days: 3,
        signalRecencyDays: 19,
        contradictionDetected: true,
      },
    },
  },
];

export function getDefaultApplicantProfileInput(): ApplicantProfileInput {
  return structuredClone(demoScenarios[0].input);
}

export function getDemoScenario(key: string): DemoScenario {
  return demoScenarios.find((scenario) => scenario.key === key) ?? demoScenarios[0];
}
