import { getDefaultApplicantProfileInput } from "@/lib/demo-scenarios";
import type { EvaluationCaseFixture } from "@/lib/types";

const base = getDefaultApplicantProfileInput();

export const syntheticEvaluationCases: EvaluationCaseFixture[] = [
  {
    id: "strong_applicant_v1",
    title: "Strong applicant",
    purpose: "Golden-path regression coverage with verified evidence across core categories.",
    tags: ["tenant_screening", "high_confidence", "verified_evidence"],
    schemaVersion: "credora.fixture.v1",
    rubricVersion: "credora-rubric-v3",
    input: structuredClone(base),
    expected: {
      recommendationStatus: "Recommended",
      confidence: "High",
      overallBand: "Strong",
      scoreRange: { min: 75, max: 100 },
      forbiddenReasonCodes: ["contradiction_detected", "insufficient_verified_coverage"],
      expectedCategoryBands: {
        identity_confidence: "Strong",
        housing_history: "Strong",
        income_stability: "Strong",
      },
      minimumEvidenceUsed: 5,
      expectedProvider: "deterministic",
      expectedMode: "deterministic_only",
      expectFallbackUsed: false,
      maximumWarnings: 1,
    },
  },
  {
    id: "thin_file_promising_v1",
    title: "Thin-file but promising applicant",
    purpose: "Ensures limited evidence lowers confidence without implying negative behavior.",
    tags: ["tenant_screening", "thin_file", "fairness"],
    schemaVersion: "credora.fixture.v1",
    rubricVersion: "credora-rubric-v3",
    input: {
      ...structuredClone(base),
      personalInformation: {
        ...base.personalInformation,
        fullName: "Amina Noor",
        email: "amina@example.com",
      },
      identityVerification: {
        ...base.identityVerification,
        identityVerified: false,
        governmentIdFileNames: [],
      },
      employmentIncome: {
        ...base.employmentIncome,
        monthlyIncome: 4200,
        payStubFileNames: [],
      },
      housingHistory: {
        ...base.housingHistory,
        leaseFileNames: [],
        rentLedgerFileNames: ["rent-receipts-q2.pdf"],
        receiptsFileNames: [],
      },
      financialStability: {
        ...base.financialStability,
        bankConnected: false,
      },
    },
    expected: {
      recommendationStatus: "Insufficient evidence",
      confidence: "Low",
      overallBand: "Moderate",
      expectedReasonCodes: ["thin_file_profile"],
      expectedCategoryBands: {
        identity_confidence: "Unknown",
        housing_history: "Strong",
      },
      expectedProvider: "deterministic",
      expectedMode: "deterministic_only",
      expectFallbackUsed: false,
      maximumWarnings: 1,
    },
  },
  {
    id: "gig_worker_volatility_v1",
    title: "Gig worker with income volatility",
    purpose: "Validates that irregular income routes to manual review instead of a blanket negative result.",
    tags: ["tenant_screening", "gig_worker", "volatility"],
    schemaVersion: "credora.fixture.v1",
    rubricVersion: "credora-rubric-v3",
    input: {
      ...structuredClone(base),
      personalInformation: {
        ...base.personalInformation,
        fullName: "Samira Patel",
        email: "samira@example.com",
        targetRent: 1650,
      },
      employmentIncome: {
        ...base.employmentIncome,
        employmentStatus: "gig_worker",
        employerName: "",
        monthlyIncome: 4700,
        incomeType: "gig",
        payFrequency: "irregular",
        payStubFileNames: [],
        contractDocumentFileNames: ["platform-payout-summary.pdf"],
      },
      financialStability: {
        ...base.financialStability,
        averageBalanceCushion: 1600,
        overdraftsLast90Days: 1,
      },
    },
    expected: {
      recommendationStatus: "Needs manual review",
      confidence: "Medium",
      overallBand: "Moderate",
      expectedReasonCodes: ["recent_overdrafts_disclosed"],
      expectedCategoryBands: {
        income_stability: "Moderate",
        housing_history: "Strong",
      },
      expectedProvider: "deterministic",
      expectedMode: "deterministic_only",
      expectFallbackUsed: false,
      maximumWarnings: 1,
    },
  },
  {
    id: "inconsistent_applicant_v1",
    title: "Applicant with contradiction",
    purpose: "Ensures contradictions outrank otherwise positive signals.",
    tags: ["tenant_screening", "contradiction", "manual_review"],
    schemaVersion: "credora.fixture.v1",
    rubricVersion: "credora-rubric-v3",
    input: {
      ...structuredClone(base),
      personalInformation: {
        ...base.personalInformation,
        fullName: "Luis Romero",
        email: "luis@example.com",
      },
      identityVerification: {
        ...base.identityVerification,
        accountOwnerMatch: false,
      },
      financialStability: {
        ...base.financialStability,
        contradictionDetected: true,
        overdraftsLast90Days: 2,
      },
    },
    expected: {
      recommendationStatus: "Potential inconsistency detected",
      confidence: "Low",
      overallBand: "Moderate",
      expectedReasonCodes: ["contradiction_detected"],
      expectedCategoryBands: {
        identity_confidence: "Moderate",
      },
      expectedProvider: "deterministic",
      expectedMode: "deterministic_only",
      expectFallbackUsed: false,
      maximumWarnings: 1,
    },
  },
  {
    id: "insufficient_evidence_v1",
    title: "Insufficient evidence case",
    purpose: "Verifies that sparse profiles become insufficient rather than weakly negative.",
    tags: ["tenant_screening", "insufficient_evidence"],
    schemaVersion: "credora.fixture.v1",
    rubricVersion: "credora-rubric-v3",
    input: {
      ...structuredClone(base),
      identityVerification: {
        ...base.identityVerification,
        identityVerified: false,
        governmentIdFileNames: [],
      },
      employmentIncome: {
        ...base.employmentIncome,
        payStubFileNames: [],
        contractDocumentFileNames: [],
      },
      housingHistory: {
        ...base.housingHistory,
        leaseFileNames: [],
        rentLedgerFileNames: [],
        receiptsFileNames: [],
        landlordReferenceName: "",
      },
      financialStability: {
        ...base.financialStability,
        bankConnected: false,
      },
    },
    expected: {
      recommendationStatus: "Insufficient evidence",
      confidence: "Low",
      overallBand: "Moderate",
      expectedReasonCodes: ["insufficient_verified_coverage"],
      expectedCategoryBands: {
        identity_confidence: "Unknown",
        housing_history: "Unknown",
        financial_stability: "Unknown",
      },
      expectedProvider: "deterministic",
      expectedMode: "deterministic_only",
      expectFallbackUsed: false,
      maximumWarnings: 1,
    },
  },
  {
    id: "student_newcomer_v1",
    title: "Student or newcomer profile",
    purpose: "Shows that short history stays reviewable without pretending the user is risky.",
    tags: ["tenant_screening", "student", "newcomer", "thin_file"],
    schemaVersion: "credora.fixture.v1",
    rubricVersion: "credora-rubric-v3",
    input: {
      ...structuredClone(base),
      personalInformation: {
        ...base.personalInformation,
        fullName: "Maya Chen",
        email: "maya@example.com",
        targetRent: 1300,
      },
      employmentIncome: {
        ...base.employmentIncome,
        employmentStatus: "student",
        employerName: "Campus Library",
        monthlyIncome: 2450,
        incomeType: "mixed",
        payFrequency: "monthly",
        payStubFileNames: ["campus-job-letter.pdf"],
        contractDocumentFileNames: [],
      },
      housingHistory: {
        ...base.housingHistory,
        currentRent: 1100,
        monthsAtResidence: 5,
        rentPaymentStreakMonths: 3,
        utilityPaymentStreakMonths: 1,
        leaseFileNames: [],
        rentLedgerFileNames: ["roommate-ledger.pdf"],
        landlordReferenceName: "",
      },
      financialStability: {
        ...base.financialStability,
        averageBalanceCushion: 950,
        overdraftsLast90Days: 1,
      },
    },
    expected: {
      recommendationStatus: "Needs manual review",
      confidence: "Medium",
      overallBand: "Moderate",
      expectedReasonCodes: ["recent_overdrafts_disclosed"],
      expectedCategoryBands: {
        housing_history: "Weak",
        income_stability: "Moderate",
      },
      expectedProvider: "deterministic",
      expectedMode: "deterministic_only",
      expectFallbackUsed: false,
      maximumWarnings: 1,
    },
  },
  {
    id: "high_score_low_confidence_v1",
    title: "High score but low confidence",
    purpose: "Ensures sparse but positive signals do not become an overconfident recommendation.",
    tags: ["tenant_screening", "coverage_cap", "confidence_gate"],
    schemaVersion: "credora.fixture.v1",
    rubricVersion: "credora-rubric-v3",
    input: {
      ...structuredClone(base),
      personalInformation: {
        ...base.personalInformation,
        fullName: "Diego Alvarez",
        email: "diego@example.com",
      },
      employmentIncome: {
        ...base.employmentIncome,
        payStubFileNames: [],
        contractDocumentFileNames: [],
        monthlyIncome: 6100,
      },
      financialStability: {
        ...base.financialStability,
        bankConnected: false,
        averageBalanceCushion: 0,
      },
      housingHistory: {
        ...base.housingHistory,
        rentLedgerFileNames: ["rent-ledger-q2.pdf"],
        receiptsFileNames: [],
      },
    },
    expected: {
      recommendationStatus: "Needs manual review",
      confidence: "Low",
      overallBand: "Moderate",
      expectedReasonCodes: ["missing_verified_income_docs", "missing_bank_signal"],
      forbiddenReasonCodes: ["contradiction_detected"],
      expectedCategoryBands: {
        housing_history: "Strong",
        income_stability: "Unknown",
        financial_stability: "Unknown",
      },
      expectedProvider: "deterministic",
      expectedMode: "deterministic_only",
      expectFallbackUsed: false,
      maximumWarnings: 1,
    },
  },
];
